[build]
  publish = "dist"
  command = "npm run export"

[context.production]
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }

[context.deploy-preview]
  environment = { NETLIFY_NEXT_PLUGIN_SKIP = "true" }